# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    dofbot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    dofbot_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

dofbot_arm_controller:
  ros__parameters:
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
dofbot_gripper_controller:
  ros__parameters:
    joint: grip_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity